
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package ve.edu.unet;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int POW = 34;
  public static final int FUNCTION = 10;
  public static final int LBRACKET = 41;
  public static final int OVER = 28;
  public static final int GE = 31;
  public static final int SEMI = 40;
  public static final int LPAREN = 38;
  public static final int CONTINUE = 21;
  public static final int REPEAT = 6;
  public static final int ARRAY = 16;
  public static final int FOR = 17;
  public static final int MINUS = 26;
  public static final int WRITE = 9;
  public static final int RPAREN = 39;
  public static final int NOT = 37;
  public static final int AND = 35;
  public static final int LT = 24;
  public static final int OR = 36;
  public static final int COMMA = 45;
  public static final int CALL = 12;
  public static final int BEGIN = 13;
  public static final int UNTIL = 7;
  public static final int NUM = 48;
  public static final int PLUS = 25;
  public static final int ASSIGN = 22;
  public static final int IF = 2;
  public static final int ID = 47;
  public static final int LE = 30;
  public static final int EOF = 0;
  public static final int RETURN = 11;
  public static final int RBRACKET = 42;
  public static final int error = 1;
  public static final int MOD = 33;
  public static final int GLOBAL = 15;
  public static final int BREAK = 20;
  public static final int EQ = 23;
  public static final int REAL = 49;
  public static final int TIMES = 27;
  public static final int COLON = 46;
  public static final int LBRACE = 43;
  public static final int ELSE = 4;
  public static final int READ = 8;
  public static final int TO = 18;
  public static final int RBRACE = 44;
  public static final int THEN = 3;
  public static final int NE = 32;
  public static final int END = 5;
  public static final int STRING = 50;
  public static final int GT = 29;
  public static final int VAR = 14;
  public static final int STEP = 19;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IF",
  "THEN",
  "ELSE",
  "END",
  "REPEAT",
  "UNTIL",
  "READ",
  "WRITE",
  "FUNCTION",
  "RETURN",
  "CALL",
  "BEGIN",
  "VAR",
  "GLOBAL",
  "ARRAY",
  "FOR",
  "TO",
  "STEP",
  "BREAK",
  "CONTINUE",
  "ASSIGN",
  "EQ",
  "LT",
  "PLUS",
  "MINUS",
  "TIMES",
  "OVER",
  "GT",
  "LE",
  "GE",
  "NE",
  "MOD",
  "POW",
  "AND",
  "OR",
  "NOT",
  "LPAREN",
  "RPAREN",
  "SEMI",
  "LBRACKET",
  "RBRACKET",
  "LBRACE",
  "RBRACE",
  "COMMA",
  "COLON",
  "ID",
  "NUM",
  "REAL",
  "STRING"
  };
}

